import 'package:flutter/material.dart';

import '../core/link.dart';
import '../ui/dispatch_ui.dart';
import 'dispatch_controller.dart';

/// Pair & Share dashboard section.
///
/// Lists currently-paired peers (each one a [LinkKind.paired] entry in
/// the policy), and offers the two affordances the spec calls for:
///
///   - **Host a session** — starts advertising via the platform Bonjour
///     bridge and shows the 6-digit verification code generated by the
///     [PairSession] when a joiner connects.
///   - **Join a session** — opens a dialog with the host's QR / 6-digit
///     code, then runs the joiner half of the handshake.
///
/// The discovery half (Bonjour) lives in `lib/paired/paired_channel.dart`
/// and is host-platform specific. For Phase 13 the UI is wired against
/// the controller's `attachPairedLink` / `detachPairedLink` setters so
/// it's testable without the platform bridge; production builds inject a
/// `PairedMethodChannelDiscovery` from the platform layer.
class PairShareSection extends StatelessWidget {
  final DispatchController controller;

  const PairShareSection({required this.controller, super.key});

  @override
  Widget build(BuildContext context) {
    List<Link> paired = controller.settings.policy.links
        .where((Link l) => l.kind == LinkKind.paired)
        .toList(growable: false);

    return DispatchSection(
      title: 'Pair & Share',
      trailing: TextButton.icon(
        onPressed: () => _showHostDialog(context),
        icon: const Icon(Icons.qr_code_2, size: 18),
        label: const Text('Host a session'),
      ),
      child: Column(
        children: <Widget>[
          if (paired.isEmpty)
            Padding(
              padding: const EdgeInsets.fromLTRB(12, 14, 12, 12),
              child: Text(
                'No paired peers yet. Host a session here and run the joiner '
                'on the other device, or tap "Host a session" on the other '
                'device and use this one to join.',
                style: Theme.of(context).textTheme.bodySmall,
              ),
            )
          else
            ...paired.map((Link l) => _PairedRow(
                  controller: controller,
                  link: l,
                )),
        ],
      ),
    );
  }

  void _showHostDialog(BuildContext context) {
    showDialog<void>(
      context: context,
      builder: (BuildContext ctx) => const _HostDialog(),
    );
  }
}

class _PairedRow extends StatelessWidget {
  final DispatchController controller;
  final Link link;

  const _PairedRow({required this.controller, required this.link});

  @override
  Widget build(BuildContext context) {
    String fp = link.pairedFingerprint ?? '—';
    String endpoint = link.pairedEndpoint ?? '—';
    return Padding(
      padding: const EdgeInsets.fromLTRB(12, 10, 12, 10),
      child: Row(
        children: <Widget>[
          const Icon(Icons.devices_other,
              color: DispatchColors.accent, size: 18),
          const SizedBox(width: 8),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Text(
                  link.label,
                  style: Theme.of(context).textTheme.bodyMedium,
                ),
                const SizedBox(height: 2),
                Text(
                  '$endpoint  · fp ${_shortFp(fp)}',
                  style: Theme.of(context).textTheme.bodySmall,
                ),
              ],
            ),
          ),
          DispatchBadge(
            label: _priorityLabel(link.priority),
            color: DispatchColors.muted,
          ),
          const SizedBox(width: 6),
          IconButton(
            icon: const Icon(Icons.link_off, size: 18),
            tooltip: 'Unpair',
            onPressed: () => controller.detachPairedLink(link.id),
          ),
        ],
      ),
    );
  }

  String _shortFp(String fp) {
    if (fp.length <= 8) return fp;
    return fp.substring(0, 8);
  }

  String _priorityLabel(LinkPriority p) {
    switch (p) {
      case LinkPriority.primary:
        return 'Primary';
      case LinkPriority.secondary:
        return 'Secondary';
      case LinkPriority.backup:
        return 'Backup';
      case LinkPriority.never:
        return 'Never';
    }
  }
}

class _HostDialog extends StatelessWidget {
  const _HostDialog();

  @override
  Widget build(BuildContext context) {
    // The actual handshake fires when a remote joiner connects via
    // Bonjour discovery. For Phase 13 the host advertises through
    // `PairedMethodChannelDiscovery` (injected by the platform layer);
    // this dialog is the UI affordance that surfaces the verification
    // code the moment a session is being negotiated.
    return AlertDialog(
      title: const Text('Host a Pair & Share session'),
      content: SizedBox(
        width: 360,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const Text(
              'This Mac will advertise on the local network. When the joiner '
              'device sees your advertisement, both screens will display the '
              'same 6-digit code. Confirm on both sides to complete pairing.',
            ),
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: DispatchColors.surface,
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: DispatchColors.border),
              ),
              child: const Center(
                child: Text(
                  'Waiting for joiner…',
                  style: TextStyle(
                    fontFamily: 'SF Mono',
                    fontSize: 18,
                    color: DispatchColors.muted,
                  ),
                ),
              ),
            ),
            const SizedBox(height: 12),
            const Text(
              'Tip: run `arcane-dispatch pair join` on the other Mac, or use '
              'the "Join" button in its Pair & Share panel.',
              style: TextStyle(color: DispatchColors.muted, fontSize: 12),
            ),
          ],
        ),
      ),
      actions: <Widget>[
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Close'),
        ),
      ],
    );
  }
}
